- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  user: root
  become: yes  # Run tasks with sudo privileges
  vars:
    ansible_python_interpreter: /bin/python3

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petshop/

    - name: tag image
      command: docker tag petstore:latest ratnakumar/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: ratnakumar
        password: mkjayarao12

    - name: Push image
      command: docker push ratnakumar/petstore:latest
 
    - name: Run container
      command: docker run -d --name pet1 --restart always -p 8082:8080 ratnakumar/petstore:latest
