- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  user: root
  become: yes  # Run tasks with sudo privileges
  vars:
    ansible_python_interpreter: /bin/python3

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petshop/

    - name: tag image
      command: docker tag petstore:latest ratnakumar/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: mounika719
        password: Mounika@1234

    - name: Push image
      command: docker push mounika719/petstore:latest
 
    - name: Run container
      command: docker run -d --name petstor2 --restart=always -p 8081:8080 mounika719/petstore:latest
